### ISSUE TITLE
Training outpace with different seeds

### ISSUE THREAD

**Issue by erdiphd** [jayLEE0301/outpace_official#2]
To be able to reproduce the similar result of outpace shown in the paper.

Should I change the seed number here (in line 9 ) then run couple of time or run couple of time without changing the seed number
https://github.com/jayLEE0301/outpace_official/blob/main/config/config_outpace.yaml#L9

![image](https://github.com/jayLEE0301/outpace_official/assets/81103451/2d68a054-5380-4325-a11c-080fdd86e0ba)

Thanks

**Comment by jayLEE0301** [comment]
Yes, we changed the seed number to get the results, and calculated variance between the results to draw the main graphs.
Thank you.
