### ISSUE TITLE
Question regarding how intermediate goal sampling is done to reach eventual final goal in PointUMaze

### ISSUE THREAD

**Issue by touranisatyajit** [jayLEE0301/outpace_official#3]
Hi first of all I would like to congratulate you for this amazing work!

I have a doubt wrt **PointUMaze**:

Could you please explain the noise addition procedure to the initial position of this environment which eventually leads to the final goal **(0, 8)**? I tried adding noise as per my understanding(curriculum_goal = curriculum_goal + noise -> this is done for many steps) to the initial position but it did not end up reaching the final goal. Could you also please point out in the code where this is happening?

Also a general doubt: Do you think this method can be applied to an environment which contains dynamic elements like cars/pedestrians/moving-objects?

Help regarding this would be appreciated. Thank you in advance!

**Comment by jayLEE0301** [comment]
Thank you for having an interest in our research!

OUTPACE utilizes initial distribution and final goal distribution to learn the CNML (each represents the discovered area and goal area respectively, at the initial stage of the learning).
To obtain the goal distribution, we add uniform noise to the default goal point [0, 8].
(see page 14 ( A.2 ENVIRONMENT DETAILS) in our paper)


The code corresponding to this is in lines 546-565 in our code (outpace_train.py)
https://github.com/jayLEE0301/outpace_official/blob/main/outpace_train.py

**Comment by touranisatyajit** [comment]
Thanks for your reply!
